# Generated by Django 3.1.7 on 2021-03-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food_index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.IntegerField(unique=True)),
                ('u_name', models.CharField(max_length=50)),
                ('batch_id', models.CharField(max_length=50)),
                ('supplier', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=50)),
                ('food_category', models.CharField(max_length=50)),
                ('food_name', models.CharField(max_length=50)),
            ],
        ),
    ]
